# Generated by Django 6.0 on 2025-12-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_cita_event_id_calendarcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='tipo',
            field=models.CharField(choices=[('normal_2', 'Normal 2 personas'), ('normal_4', 'Normal 4 personas'), ('vip_2', 'VIP 2 personas'), ('vip_grande', 'VIP 5-12 personas'), ('cumple_10', 'Cumpleanos 10+ personas')], max_length=20),
        ),
    ]
